In [1]:
import pandas as pd

In [2]:
url = 'https://github.com/mattharrison/datasets/raw/master/data/siena2018-pres.csv'

In [3]:
def tweak_siena_pres(df):
    def int64_to_uint8(df_):
        cols = df_.select_dtypes('int64')
        return (df_
                .astype({col:'uint8[pyarrow]' for col in cols}))
    return (df
            .rename(columns={'Seq.': 'Seq'}) # 1
            .rename(columns={k:v.replace(' ', '_') for k,v in
                             {'Bg': 'Background',
                              'PL': 'Party leadership', 'CAb': 'Communication ability',
                              'RC': 'Relations with Congress', 'CAp': 'Court appointments',
                              'HE': 'Handling of economy', 'L': 'Luck',
                              'AC': 'Ability to compromise', 'WR': 'Willing to take risks',
                              'EAp': 'Executive appointments', 'OA': 'Overall ability',
                              'Im': 'Imagination', 'DA': 'Domestic accomplishments',
                              'Int': 'Integrity', 'EAb': 'Executive ability',
                              'FPA': 'Foreign policy accomplishments',
                              'LA': 'Leadership ability',
                              'IQ': 'Intelligence', 'AM': 'Avoid crucial mistakes',
                              'EV': "Experts' view", 'O': 'Overall'}.items()})
                              .astype({'Party':'category'})  # 2
                              .pipe(int64_to_uint8)  # 3
                              .assign(Average_rank=lambda df_:(df_.select_dtypes('uint8')
                                                               .sum(axis=1).rank(method='dense').astype('uint8[pyarrow]')),
                                                               Quartile=lambda df_:pd.qcut(df_.Average_rank, 4,
                                                                                           labels='1st 2nd 3rd 4th'.split())
                                    )
    )

In [4]:
df = pd.read_csv(url, index_col=0, dtype_backend='pyarrow')
pres = tweak_siena_pres(df)

In [5]:
def name_to_initial(val):
    names = val.split()
    return ' '.join([f'{names[0][0]}.', *names[1:]])

In [6]:
(pres
      .set_index('President')
      .rename(name_to_initial))

,Seq,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,Executive_ability,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
President,,,,,,,,,,,,,,,,,,,,,
G. Washington,1,Independent,7,7,1,10,1,6,2,2,...,1,1,1,2,2,1,2,1,1,1st
J. Adams,2,Federalist,3,13,4,4,24,14,31,21,...,4,13,15,19,13,16,10,14,13,2nd
T. Jefferson,3,Democratic-Republican,2,2,14,1,8,5,14,6,...,7,20,4,6,9,7,5,5,5,1st
J. Madison,4,Democratic-Republican,4,6,7,3,16,15,6,13,...,6,14,7,11,19,11,8,7,7,1st
J. Monroe,5,Democratic-Republican,9,14,11,18,6,16,7,10,...,11,9,9,10,5,6,9,8,8,1st
J. Quincy Adams,6,Democratic-Republican,1,9,6,5,29,19,24,22,...,15,17,18,21,15,14,18,18,18,2nd
A. Jackson,7,Democratic,37,15,29,28,4,4,38,11,...,30,25,25,17,23,20,19,19,19,2nd
M. Van Buren,8,Democratic,23,22,27,25,34,28,20,28,...,25,31,26,29,27,24,28,25,25,3rd
W. Henry Harrison,9,Whig,22,38,28,37,44,32,41,38,...,42,41,40,42,44,37,39,39,38,4th
J. Tyler,10,Independent,34,33,35,34,22,26,37,36,...,38,34,36,36,26,32,36,37,37,4th
J. K. Polk,11,Democratic,19,10,23,23,9,7,18,7,...,22,15,16,12,8,8,13,12,11,1st
Z. Taylor,12,Whig,30,26,22,32,37,24,26,26,...,37,27,33,27,30,26,30,30,30,3rd
M. Fillmore,13,Whig,40,37,36,38,35,38,32,37,...,39,37,37,37,37,33,37,38,39,4th
F. Pierce,14,Democratic,38,39,38,40,39,38,39,39,...,41,40,39,41,39,38,40,40,41,4th
J. Buchanan,15,Democratic,36,43,40,39,42,41,40,42,...,43,42,43,44,43,44,44,43,43,4th
A. Lincoln,16,Republican,28,1,2,2,18,1,1,1,...,3,4,2,1,6,2,1,3,3,1st
A. Johnson,17,Democratic,42,42,41,42,40,34,43,43,...,44,43,42,43,41,43,43,44,44,4th
U. S. Grant,18,Republican,20,24,25,24,26,18,17,27,...,24,26,38,24,24,31,24,24,24,3rd
R. B. Hayes,19,Republican,35,30,32,29,23,35,23,33,...,27,22,30,35,31,28,29,32,32,3rd
J. A. Garfield,20,Republican,22,25,21,20,41,30,25,25,...,34,29,27,34,34,27,25,28,29,3rd
C. A. Arthur,21,Republican,41,31,37,36,17,33,22,30,...,33,30,31,25,32,23,31,34,34,4th
G. Cleveland,22/24,Democratic,26,23,26,27,19,27,22,19,...,20,21,23,23,21,15,22,23,23,3rd
B. Harrison,23,Republican,33,34,30,35,28,36,33,35,...,35,32,34,32,29,29,33,35,36,4th
W. McKinley,25,Republican,29,20,20,26,32,22,21,17,...,23,16,17,20,14,13,20,20,20,2nd
T. Roosevelt,26,Republican,5,4,8,6,2,2,15,4,...,9,3,5,4,3,5,4,4,4,1st
W. Howard Taft,27,Republican,12,28,12,14,27,31,19,23,...,16,19,21,18,22,19,23,22,22,2nd
W. Wilson,28,Democratic,8,8,19,7,14,11,35,14,...,13,11,14,14,11,25,15,11,12,2nd
W. G. Harding,29,Republican,39,41,42,43,33,40,34,40,...,36,35,41,38,36,39,41,41,40,4th
C. Coolidge,30,Republican,32,36,17,33,13,39,27,32,...,31,24,32,33,35,22,32,31,31,3rd
H. Hoover,31,Republican,13,35,15,13,43,37,36,29,...,26,44,35,39,33,40,35,36,35,4th
F. D. Roosevelt,32,Democratic,6,3,16,12,5,3,4,3,...,2,2,3,3,1,4,3,2,2,1st
H. S. Truman,33,Democratic,31,16,9,21,12,8,12,8,...,17,8,10,7,4,9,7,9,9,1st
D. D. Eisenhower,34,Republican,11,18,5,17,7,21,5,5,...,5,6,11,8,7,3,6,6,6,1st
J. F. Kennedy,35,Democratic,14,5,31,11,31,9,8,12,...,12,7,6,15,17,18,12,10,10,1st
L. B. Johnson,36,Democratic,15,11,34,22,25,10,9,9,...,8,12,8,5,40,35,17,16,16,2nd
R. Nixon,37,Republican,16,21,43,16,36,12,30,24,...,32,23,28,22,16,42,38,29,28,3rd
G. Ford,38,Republican,18,32,10,30,30,29,11,31,...,21,33,24,31,28,21,27,27,26,3rd
J. Carter,39,Democratic,25,19,3,15,38,27,29,32,...,19,38,22,28,25,34,26,26,27,3rd
R. Reagan,40,Republican,27,17,24,31,3,13,10,15,...,18,18,20,16,12,12,16,13,14,2nd
G. H. W. Bush,41,Republican,10,27,18,19,20,27,13,20,...,29,28,19,26,10,17,21,21,21,2nd
B. Clinton,42,Democratic,21,12,39,8,11,17,3,16,...,10,5,12,9,18,30,14,15,15,2nd
G. W. Bush,43,Republican,17,29,33,41,21,20,28,34,...,28,36,29,30,38,36,34,33,33,3rd
B. Obama,44,Democratic,24,11,13,9,15,23,16,18,...,14,10,13,13,20,10,11,17,17,2nd
D. Trump,45,Republican,43,40,44,44,10,25,42,41,...,40,39,44,40,42,41,42,42,42,4th

In [7]:
(pres
 .set_index('President')
 .reset_index())

,President,Seq,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
0,George Washington,1,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
1,John Adams,2,Federalist,3,13,4,4,24,14,31,...,4,13,15,19,13,16,10,14,13,2nd
2,Thomas Jefferson,3,Democratic-Republican,2,2,14,1,8,5,14,...,7,20,4,6,9,7,5,5,5,1st
3,James Madison,4,Democratic-Republican,4,6,7,3,16,15,6,...,6,14,7,11,19,11,8,7,7,1st
4,James Monroe,5,Democratic-Republican,9,14,11,18,6,16,7,...,11,9,9,10,5,6,9,8,8,1st
5,John Quincy Adams,6,Democratic-Republican,1,9,6,5,29,19,24,...,15,17,18,21,15,14,18,18,18,2nd
6,Andrew Jackson,7,Democratic,37,15,29,28,4,4,38,...,30,25,25,17,23,20,19,19,19,2nd
7,Martin Van Buren,8,Democratic,23,22,27,25,34,28,20,...,25,31,26,29,27,24,28,25,25,3rd
8,William Henry Harrison,9,Whig,22,38,28,37,44,32,41,...,42,41,40,42,44,37,39,39,38,4th
9,John Tyler,10,Independent,34,33,35,34,22,26,37,...,38,34,36,36,26,32,36,37,37,4th
10,James K. Polk,11,Democratic,19,10,23,23,9,7,18,...,22,15,16,12,8,8,13,12,11,1st
11,Zachary Taylor,12,Whig,30,26,22,32,37,24,26,...,37,27,33,27,30,26,30,30,30,3rd
12,Millard Fillmore,13,Whig,40,37,36,38,35,38,32,...,39,37,37,37,37,33,37,38,39,4th
13,Franklin Pierce,14,Democratic,38,39,38,40,39,38,39,...,41,40,39,41,39,38,40,40,41,4th
14,James Buchanan,15,Democratic,36,43,40,39,42,41,40,...,43,42,43,44,43,44,44,43,43,4th
15,Abraham Lincoln,16,Republican,28,1,2,2,18,1,1,...,3,4,2,1,6,2,1,3,3,1st
16,Andrew Johnson,17,Democratic,42,42,41,42,40,34,43,...,44,43,42,43,41,43,43,44,44,4th
17,Ulysses S. Grant,18,Republican,20,24,25,24,26,18,17,...,24,26,38,24,24,31,24,24,24,3rd
18,Rutherford B. Hayes,19,Republican,35,30,32,29,23,35,23,...,27,22,30,35,31,28,29,32,32,3rd
19,James A. Garfield,20,Republican,22,25,21,20,41,30,25,...,34,29,27,34,34,27,25,28,29,3rd
20,Chester A. Arthur,21,Republican,41,31,37,36,17,33,22,...,33,30,31,25,32,23,31,34,34,4th
21,Grover Cleveland,22/24,Democratic,26,23,26,27,19,27,22,...,20,21,23,23,21,15,22,23,23,3rd
22,Benjamin Harrison,23,Republican,33,34,30,35,28,36,33,...,35,32,34,32,29,29,33,35,36,4th
23,William McKinley,25,Republican,29,20,20,26,32,22,21,...,23,16,17,20,14,13,20,20,20,2nd
24,Theodore Roosevelt,26,Republican,5,4,8,6,2,2,15,...,9,3,5,4,3,5,4,4,4,1st
25,William Howard Taft,27,Republican,12,28,12,14,27,31,19,...,16,19,21,18,22,19,23,22,22,2nd
26,Woodrow Wilson,28,Democratic,8,8,19,7,14,11,35,...,13,11,14,14,11,25,15,11,12,2nd
27,Warren G. Harding,29,Republican,39,41,42,43,33,40,34,...,36,35,41,38,36,39,41,41,40,4th
28,Calvin Coolidge,30,Republican,32,36,17,33,13,39,27,...,31,24,32,33,35,22,32,31,31,3rd
29,Herbert Hoover,31,Republican,13,35,15,13,43,37,36,...,26,44,35,39,33,40,35,36,35,4th
30,Franklin D. Roosevelt,32,Democratic,6,3,16,12,5,3,4,...,2,2,3,3,1,4,3,2,2,1st
31,Harry S. Truman,33,Democratic,31,16,9,21,12,8,12,...,17,8,10,7,4,9,7,9,9,1st
32,Dwight D. Eisenhower,34,Republican,11,18,5,17,7,21,5,...,5,6,11,8,7,3,6,6,6,1st
33,John F. Kennedy,35,Democratic,14,5,31,11,31,9,8,...,12,7,6,15,17,18,12,10,10,1st
34,Lyndon B. Johnson,36,Democratic,15,11,34,22,25,10,9,...,8,12,8,5,40,35,17,16,16,2nd
35,Richard Nixon,37,Republican,16,21,43,16,36,12,30,...,32,23,28,22,16,42,38,29,28,3rd
36,Gerald Ford,38,Republican,18,32,10,30,30,29,11,...,21,33,24,31,28,21,27,27,26,3rd
37,Jimmy Carter,39,Democratic,25,19,3,15,38,27,29,...,19,38,22,28,25,34,26,26,27,3rd
38,Ronald Reagan,40,Republican,27,17,24,31,3,13,10,...,18,18,20,16,12,12,16,13,14,2nd
39,George H. W. Bush,41,Republican,10,27,18,19,20,27,13,...,29,28,19,26,10,17,21,21,21,2nd
40,Bill Clinton,42,Democratic,21,12,39,8,11,17,3,...,10,5,12,9,18,30,14,15,15,2nd
41,George W. Bush,43,Republican,17,29,33,41,21,20,28,...,28,36,29,30,38,36,34,33,33,3rd
42,Barack Obama,44,Democratic,24,11,13,9,15,23,16,...,14,10,13,13,20,10,11,17,17,2nd
43,Donald Trump,45,Republican,43,40,44,44,10,25,42,...,40,39,44,40,42,41,42,42,42,4th

In [8]:
lt10 = pres.Average_rank < 10
pres[lt10]

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
3,3,Thomas Jefferson,Democratic-Republican,2,2,14,1,8,5,14,...,7,20,4,6,9,7,5,5,5,1st
4,4,James Madison,Democratic-Republican,4,6,7,3,16,15,6,...,6,14,7,11,19,11,8,7,7,1st
5,5,James Monroe,Democratic-Republican,9,14,11,18,6,16,7,...,11,9,9,10,5,6,9,8,8,1st
16,16,Abraham Lincoln,Republican,28,1,2,2,18,1,1,...,3,4,2,1,6,2,1,3,3,1st
25,26,Theodore Roosevelt,Republican,5,4,8,6,2,2,15,...,9,3,5,4,3,5,4,4,4,1st
31,32,Franklin D. Roosevelt,Democratic,6,3,16,12,5,3,4,...,2,2,3,3,1,4,3,2,2,1st
32,33,Harry S. Truman,Democratic,31,16,9,21,12,8,12,...,17,8,10,7,4,9,7,9,9,1st
33,34,Dwight D. Eisenhower,Republican,11,18,5,17,7,21,5,...,5,6,11,8,7,3,6,6,6,1st

In [9]:
(pres[lt10 & (pres.Party == 'Republican')])

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
16,16,Abraham Lincoln,Republican,28,1,2,2,18,1,1,...,3,4,2,1,6,2,1,3,3,1st
25,26,Theodore Roosevelt,Republican,5,4,8,6,2,2,15,...,9,3,5,4,3,5,4,4,4,1st
33,34,Dwight D. Eisenhower,Republican,11,18,5,17,7,21,5,...,5,6,11,8,7,3,6,6,6,1st

In [10]:
(pres.query('Average_rank < 10 and Party == "Republican"'))

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
16,16,Abraham Lincoln,Republican,28,1,2,2,18,1,1,...,3,4,2,1,6,2,1,3,3,1st
25,26,Theodore Roosevelt,Republican,5,4,8,6,2,2,15,...,9,3,5,4,3,5,4,4,4,1st
33,34,Dwight D. Eisenhower,Republican,11,18,5,17,7,21,5,...,5,6,11,8,7,3,6,6,6,1st

In [11]:
lt10 = pres.Average_rank < 10
(pres.query('@lt10 and Party == "Republican"'))

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
16,16,Abraham Lincoln,Republican,28,1,2,2,18,1,1,...,3,4,2,1,6,2,1,3,3,1st
25,26,Theodore Roosevelt,Republican,5,4,8,6,2,2,15,...,9,3,5,4,3,5,4,4,4,1st
33,34,Dwight D. Eisenhower,Republican,11,18,5,17,7,21,5,...,5,6,11,8,7,3,6,6,6,1st

In [12]:
pres.iloc[1]

Seq                                        2
President                         John Adams
Party                             Federalist
Background                                 3
Imagination                               13
Integrity                                  4
Intelligence                               4
Luck                                      24
Willing_to_take_risks                     14
Ability_to_compromise                     31
Executive_ability                         21
Leadership_ability                        21
Communication_ability                     13
Overall_ability                            8
Party_leadership                          28
Relations_with_Congress                   17
Court_appointments                         4
Handling_of_economy                       13
Executive_appointments                    15
Domestic_accomplishments                  19
Foreign_policy_accomplishments            13
Avoid_crucial_mistakes                    16
Experts'_view                             10
Overall                                   14
Average_rank                              13
Quartile                                 2nd
Name: 2, dtype: object

In [13]:
pres.iloc[[1]]

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
2,2,John Adams,Federalist,3,13,4,4,24,14,31,...,4,13,15,19,13,16,10,14,13,2nd

In [14]:
(pres.iloc[[0, 5, 10]])

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
6,6,John Quincy Adams,Democratic-Republican,1,9,6,5,29,19,24,...,15,17,18,21,15,14,18,18,18,2nd
11,11,James K. Polk,Democratic,19,10,23,23,9,7,18,...,22,15,16,12,8,8,13,12,11,1st

In [15]:
pres.iloc[0:11:5]

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
6,6,John Quincy Adams,Democratic-Republican,1,9,6,5,29,19,24,...,15,17,18,21,15,14,18,18,18,2nd
11,11,James K. Polk,Democratic,19,10,23,23,9,7,18,...,22,15,16,12,8,8,13,12,11,1st

In [16]:
pres.iloc[[0, 5, 10]]

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
6,6,John Quincy Adams,Democratic-Republican,1,9,6,5,29,19,24,...,15,17,18,21,15,14,18,18,18,2nd
11,11,James K. Polk,Democratic,19,10,23,23,9,7,18,...,22,15,16,12,8,8,13,12,11,1st

In [17]:
pres.iloc[lambda df: [0,5,10]]

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
6,6,John Quincy Adams,Democratic-Republican,1,9,6,5,29,19,24,...,15,17,18,21,15,14,18,18,18,2nd
11,11,James K. Polk,Democratic,19,10,23,23,9,7,18,...,22,15,16,12,8,8,13,12,11,1st

In [18]:
pres.iloc[[0, 5, 10], 1]

1     George Washington
6     John Quincy Adams
11        James K. Polk
Name: President, dtype: string[pyarrow]

In [19]:
pres.iloc[[0, 5, 10], [1]]

            President
1   George Washington
6   John Quincy Adams
11      James K. Polk

In [20]:
pres.iloc[:, [1,2]]

                 President                  Party
1        George Washington            Independent
2               John Adams             Federalist
3         Thomas Jefferson  Democratic-Republican
4            James Madison  Democratic-Republican
5             James Monroe  Democratic-Republican
6        John Quincy Adams  Democratic-Republican
7           Andrew Jackson             Democratic
8         Martin Van Buren             Democratic
9   William Henry Harrison                   Whig
10              John Tyler            Independent
11           James K. Polk             Democratic
12          Zachary Taylor                   Whig
13        Millard Fillmore                   Whig
14         Franklin Pierce             Democratic
15          James Buchanan             Democratic
16         Abraham Lincoln             Republican
17          Andrew Johnson             Democratic
18        Ulysses S. Grant             Republican
19     Rutherford B. Hayes             Republican
20       James A. Garfield             Republican
21       Chester A. Arthur             Republican
22        Grover Cleveland             Democratic
23       Benjamin Harrison             Republican
24        William McKinley             Republican
25      Theodore Roosevelt             Republican
26     William Howard Taft             Republican
27          Woodrow Wilson             Democratic
28       Warren G. Harding             Republican
29         Calvin Coolidge             Republican
30          Herbert Hoover             Republican
31   Franklin D. Roosevelt             Democratic
32         Harry S. Truman             Democratic
33    Dwight D. Eisenhower             Republican
34         John F. Kennedy             Democratic
35       Lyndon B. Johnson             Democratic
36           Richard Nixon             Republican
37             Gerald Ford             Republican
38            Jimmy Carter             Democratic
39           Ronald Reagan             Republican
40       George H. W. Bush             Republican
41            Bill Clinton             Democratic
42          George W. Bush             Republican
43            Barack Obama             Democratic
44            Donald Trump             Republican

In [21]:
pres.loc[1:5]

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
2,2,John Adams,Federalist,3,13,4,4,24,14,31,...,4,13,15,19,13,16,10,14,13,2nd
3,3,Thomas Jefferson,Democratic-Republican,2,2,14,1,8,5,14,...,7,20,4,6,9,7,5,5,5,1st
4,4,James Madison,Democratic-Republican,4,6,7,3,16,15,6,...,6,14,7,11,19,11,8,7,7,1st
5,5,James Monroe,Democratic-Republican,9,14,11,18,6,16,7,...,11,9,9,10,5,6,9,8,8,1st

In [22]:
pres.iloc[1:5]

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
2,2,John Adams,Federalist,3,13,4,4,24,14,31,...,4,13,15,19,13,16,10,14,13,2nd
3,3,Thomas Jefferson,Democratic-Republican,2,2,14,1,8,5,14,...,7,20,4,6,9,7,5,5,5,1st
4,4,James Madison,Democratic-Republican,4,6,7,3,16,15,6,...,6,14,7,11,19,11,8,7,7,1st
5,5,James Monroe,Democratic-Republican,9,14,11,18,6,16,7,...,11,9,9,10,5,6,9,8,8,1st

In [23]:
(pres
 .set_index('Party')
 .loc['Whig'])

,Seq,President,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,Executive_ability,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
Party,,,,,,,,,,,,,,,,,,,,,
Whig,9,William Henry Harrison,22,38,28,37,44,32,41,38,...,42,41,40,42,44,37,39,39,38,4th
Whig,12,Zachary Taylor,30,26,22,32,37,24,26,26,...,37,27,33,27,30,26,30,30,30,3rd
Whig,13,Millard Fillmore,40,37,36,38,35,38,32,37,...,39,37,37,37,37,33,37,38,39,4th

In [24]:
(pres
 .set_index('Party')
 .loc[['Whig']])

,Seq,President,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,Executive_ability,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
Party,,,,,,,,,,,,,,,,,,,,,
Whig,9,William Henry Harrison,22,38,28,37,44,32,41,38,...,42,41,40,42,44,37,39,39,38,4th
Whig,12,Zachary Taylor,30,26,22,32,37,24,26,26,...,37,27,33,27,30,26,30,30,30,3rd
Whig,13,Millard Fillmore,40,37,36,38,35,38,32,37,...,39,37,37,37,37,33,37,38,39,4th

In [25]:
(pres
 .set_index('Party')
 .loc['Federalist'])

Seq                                        2
President                         John Adams
Background                                 3
Imagination                               13
Integrity                                  4
Intelligence                               4
Luck                                      24
Willing_to_take_risks                     14
Ability_to_compromise                     31
Executive_ability                         21
Leadership_ability                        21
Communication_ability                     13
Overall_ability                            8
Party_leadership                          28
Relations_with_Congress                   17
Court_appointments                         4
Handling_of_economy                       13
Executive_appointments                    15
Domestic_accomplishments                  19
Foreign_policy_accomplishments            13
Avoid_crucial_mistakes                    16
Experts'_view                             10
Overall                                   14
Average_rank                              13
Quartile                                 2nd
Name: Federalist, dtype: object

In [26]:
(pres
 .set_index('Party')
 .loc[['Federalist']])

,Seq,President,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,Executive_ability,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
Party,,,,,,,,,,,,,,,,,,,,,
Federalist,2,John Adams,3,13,4,4,24,14,31,21,...,4,13,15,19,13,16,10,14,13,2nd

In [27]:
# (pres
#  .set_index('Party')
#  .loc['Democratic':'Independent'])



# Error

In [28]:
(pres
 .set_index('Party')
 .sort_index()
 .loc['Democratic':'Independent'])

,Seq,President,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,Executive_ability,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
Party,,,,,,,,,,,,,,,,,,,,,
Democratic,22/24,Grover Cleveland,26,23,26,27,19,27,22,19,...,20,21,23,23,21,15,22,23,23,3rd
Democratic,32,Franklin D. Roosevelt,6,3,16,12,5,3,4,3,...,2,2,3,3,1,4,3,2,2,1st
Democratic,17,Andrew Johnson,42,42,41,42,40,34,43,43,...,44,43,42,43,41,43,43,44,44,4th
Democratic,33,Harry S. Truman,31,16,9,21,12,8,12,8,...,17,8,10,7,4,9,7,9,9,1st
Democratic,15,James Buchanan,36,43,40,39,42,41,40,42,...,43,42,43,44,43,44,44,43,43,4th
Democratic,14,Franklin Pierce,38,39,38,40,39,38,39,39,...,41,40,39,41,39,38,40,40,41,4th
Democratic,35,John F. Kennedy,14,5,31,11,31,9,8,12,...,12,7,6,15,17,18,12,10,10,1st
Democratic,36,Lyndon B. Johnson,15,11,34,22,25,10,9,9,...,8,12,8,5,40,35,17,16,16,2nd
Democratic,11,James K. Polk,19,10,23,23,9,7,18,7,...,22,15,16,12,8,8,13,12,11,1st
Democratic,39,Jimmy Carter,25,19,3,15,38,27,29,32,...,19,38,22,28,25,34,26,26,27,3rd
Democratic,42,Bill Clinton,21,12,39,8,11,17,3,16,...,10,5,12,9,18,30,14,15,15,2nd
Democratic,8,Martin Van Buren,23,22,27,25,34,28,20,28,...,25,31,26,29,27,24,28,25,25,3rd
Democratic,7,Andrew Jackson,37,15,29,28,4,4,38,11,...,30,25,25,17,23,20,19,19,19,2nd
Democratic,28,Woodrow Wilson,8,8,19,7,14,11,35,14,...,13,11,14,14,11,25,15,11,12,2nd
Democratic,44,Barack Obama,24,11,13,9,15,23,16,18,...,14,10,13,13,20,10,11,17,17,2nd
Democratic-Republican,6,John Quincy Adams,1,9,6,5,29,19,24,22,...,15,17,18,21,15,14,18,18,18,2nd
Democratic-Republican,5,James Monroe,9,14,11,18,6,16,7,10,...,11,9,9,10,5,6,9,8,8,1st
Democratic-Republican,4,James Madison,4,6,7,3,16,15,6,13,...,6,14,7,11,19,11,8,7,7,1st
Democratic-Republican,3,Thomas Jefferson,2,2,14,1,8,5,14,6,...,7,20,4,6,9,7,5,5,5,1st
Federalist,2,John Adams,3,13,4,4,24,14,31,21,...,4,13,15,19,13,16,10,14,13,2nd
Independent,1,George Washington,7,7,1,10,1,6,2,2,...,1,1,1,2,2,1,2,1,1,1st
Independent,10,John Tyler,34,33,35,34,22,26,37,36,...,38,34,36,36,26,32,36,37,37,4th

In [29]:
(pres
.set_index('President')
.sort_index()
.loc['C':'Thomas Jefferson','Party':'Integrity'])

,Party,Background,Imagination,Integrity
President,,,,
Calvin Coolidge,Republican,32,36,17
Chester A. Arthur,Republican,41,31,37
Donald Trump,Republican,43,40,44
Dwight D. Eisenhower,Republican,11,18,5
Franklin D. Roosevelt,Democratic,6,3,16
Franklin Pierce,Democratic,38,39,38
George H. W. Bush,Republican,10,27,18
George W. Bush,Republican,17,29,33
George Washington,Independent,7,7,1
Gerald Ford,Republican,18,32,10
Grover Cleveland,Democratic,26,23,26
Harry S. Truman,Democratic,31,16,9
Herbert Hoover,Republican,13,35,15
James A. Garfield,Republican,22,25,21
James Buchanan,Democratic,36,43,40
James K. Polk,Democratic,19,10,23
James Madison,Democratic-Republican,4,6,7
James Monroe,Democratic-Republican,9,14,11
Jimmy Carter,Democratic,25,19,3
John Adams,Federalist,3,13,4
John F. Kennedy,Democratic,14,5,31
John Quincy Adams,Democratic-Republican,1,9,6
John Tyler,Independent,34,33,35
Lyndon B. Johnson,Democratic,15,11,34
Martin Van Buren,Democratic,23,22,27
Millard Fillmore,Whig,40,37,36
Richard Nixon,Republican,16,21,43
Ronald Reagan,Republican,27,17,24
Rutherford B. Hayes,Republican,35,30,32
Theodore Roosevelt,Republican,5,4,8
Thomas Jefferson,Democratic-Republican,2,2,14

In [30]:
# (pres
#  .set_index('Party')
#  .sort_index()
#  .loc['D':'J'])

# Error

In [31]:
import pyarrow as pa
string_pa = pd.ArrowDtype(pa.string())

In [32]:
(pres
 .assign(Party=pres.Party.astype(string_pa))
 .set_index('Party')
 .sort_index()
 .loc['D':'J'])

,Seq,President,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,Executive_ability,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
Party,,,,,,,,,,,,,,,,,,,,,
Democratic,7,Andrew Jackson,37,15,29,28,4,4,38,11,...,30,25,25,17,23,20,19,19,19,2nd
Democratic,8,Martin Van Buren,23,22,27,25,34,28,20,28,...,25,31,26,29,27,24,28,25,25,3rd
Democratic,11,James K. Polk,19,10,23,23,9,7,18,7,...,22,15,16,12,8,8,13,12,11,1st
Democratic,14,Franklin Pierce,38,39,38,40,39,38,39,39,...,41,40,39,41,39,38,40,40,41,4th
Democratic,15,James Buchanan,36,43,40,39,42,41,40,42,...,43,42,43,44,43,44,44,43,43,4th
Democratic,17,Andrew Johnson,42,42,41,42,40,34,43,43,...,44,43,42,43,41,43,43,44,44,4th
Democratic,22/24,Grover Cleveland,26,23,26,27,19,27,22,19,...,20,21,23,23,21,15,22,23,23,3rd
Democratic,28,Woodrow Wilson,8,8,19,7,14,11,35,14,...,13,11,14,14,11,25,15,11,12,2nd
Democratic,32,Franklin D. Roosevelt,6,3,16,12,5,3,4,3,...,2,2,3,3,1,4,3,2,2,1st
Democratic,33,Harry S. Truman,31,16,9,21,12,8,12,8,...,17,8,10,7,4,9,7,9,9,1st
Democratic,35,John F. Kennedy,14,5,31,11,31,9,8,12,...,12,7,6,15,17,18,12,10,10,1st
Democratic,36,Lyndon B. Johnson,15,11,34,22,25,10,9,9,...,8,12,8,5,40,35,17,16,16,2nd
Democratic,39,Jimmy Carter,25,19,3,15,38,27,29,32,...,19,38,22,28,25,34,26,26,27,3rd
Democratic,42,Bill Clinton,21,12,39,8,11,17,3,16,...,10,5,12,9,18,30,14,15,15,2nd
Democratic,44,Barack Obama,24,11,13,9,15,23,16,18,...,14,10,13,13,20,10,11,17,17,2nd
Democratic-Republican,3,Thomas Jefferson,2,2,14,1,8,5,14,6,...,7,20,4,6,9,7,5,5,5,1st
Democratic-Republican,4,James Madison,4,6,7,3,16,15,6,13,...,6,14,7,11,19,11,8,7,7,1st
Democratic-Republican,5,James Monroe,9,14,11,18,6,16,7,10,...,11,9,9,10,5,6,9,8,8,1st
Democratic-Republican,6,John Quincy Adams,1,9,6,5,29,19,24,22,...,15,17,18,21,15,14,18,18,18,2nd
Federalist,2,John Adams,3,13,4,4,24,14,31,21,...,4,13,15,19,13,16,10,14,13,2nd
Independent,1,George Washington,7,7,1,10,1,6,2,2,...,1,1,1,2,2,1,2,1,1,1st
Independent,10,John Tyler,34,33,35,34,22,26,37,36,...,38,34,36,36,26,32,36,37,37,4th

In [33]:
(pres
 .set_index('President')
 .sort_index()
 .sort_index(axis='columns')
 .loc['C':'Thomas Jefferson', 'B':'D'])

                       Background  Communication_ability  Court_appointments
President
Calvin Coolidge                32                     37                  31
Chester A. Arthur              41                     36                  33
Donald Trump                   43                     43                  40
Dwight D. Eisenhower           11                     20                   5
Franklin D. Roosevelt           6                      2                   2
Franklin Pierce                38                     41                  41
George H. W. Bush              10                     28                  29
George W. Bush                 17                     38                  28
George Washington               7                     11                   1
Gerald Ford                    18                     33                  21
Grover Cleveland               26                     19                  20
Harry S. Truman                31                     14                  17
Herbert Hoover                 13                     29                  26
James A. Garfield              22                     23                  34
James Buchanan                 36                     42                  43
James K. Polk                  19                     16                  22
James Madison                   4                     10                   6
James Monroe                    9                     15                  11
Jimmy Carter                   25                     24                  19
John Adams                      3                     13                   4
John F. Kennedy                14                      3                  12
John Quincy Adams               1                     12                  15
John Tyler                     34                     34                  38
Lyndon B. Johnson              15                     17                   8
Martin Van Buren               23                     25                  25
Millard Fillmore               40                     40                  39
Richard Nixon                  16                     27                  32
Ronald Reagan                  27                      6                  18
Rutherford B. Hayes            35                     30                  27
Theodore Roosevelt              5                      5                   9
Thomas Jefferson                2                      4                   7

In [34]:
(pres
 .loc[pres.Average_rank < 10, lambda df_: df_.columns[:3]])

   Seq              President                  Party
1    1      George Washington            Independent
3    3       Thomas Jefferson  Democratic-Republican
4    4          James Madison  Democratic-Republican
5    5           James Monroe  Democratic-Republican
16  16        Abraham Lincoln             Republican
25  26     Theodore Roosevelt             Republican
31  32  Franklin D. Roosevelt             Democratic
32  33        Harry S. Truman             Democratic
33  34   Dwight D. Eisenhower             Republican

In [35]:
# Exercise 1:
# Pull out the first two rows by name.
(pres
 .set_index('President')
 .loc[['George Washington', 'John Adams']])

,Seq,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,Executive_ability,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
President,,,,,,,,,,,,,,,,,,,,,
George Washington,1,Independent,7,7,1,10,1,6,2,2,...,1,1,1,2,2,1,2,1,1,1st
John Adams,2,Federalist,3,13,4,4,24,14,31,21,...,4,13,15,19,13,16,10,14,13,2nd

In [36]:
# Exercise 2:
# Pull out the first two rows by position.
(pres
 .iloc[0:2])

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
2,2,John Adams,Federalist,3,13,4,4,24,14,31,...,4,13,15,19,13,16,10,14,13,2nd

In [39]:
pres

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
2,2,John Adams,Federalist,3,13,4,4,24,14,31,...,4,13,15,19,13,16,10,14,13,2nd
3,3,Thomas Jefferson,Democratic-Republican,2,2,14,1,8,5,14,...,7,20,4,6,9,7,5,5,5,1st
4,4,James Madison,Democratic-Republican,4,6,7,3,16,15,6,...,6,14,7,11,19,11,8,7,7,1st
5,5,James Monroe,Democratic-Republican,9,14,11,18,6,16,7,...,11,9,9,10,5,6,9,8,8,1st
6,6,John Quincy Adams,Democratic-Republican,1,9,6,5,29,19,24,...,15,17,18,21,15,14,18,18,18,2nd
7,7,Andrew Jackson,Democratic,37,15,29,28,4,4,38,...,30,25,25,17,23,20,19,19,19,2nd
8,8,Martin Van Buren,Democratic,23,22,27,25,34,28,20,...,25,31,26,29,27,24,28,25,25,3rd
9,9,William Henry Harrison,Whig,22,38,28,37,44,32,41,...,42,41,40,42,44,37,39,39,38,4th
10,10,John Tyler,Independent,34,33,35,34,22,26,37,...,38,34,36,36,26,32,36,37,37,4th
11,11,James K. Polk,Democratic,19,10,23,23,9,7,18,...,22,15,16,12,8,8,13,12,11,1st
12,12,Zachary Taylor,Whig,30,26,22,32,37,24,26,...,37,27,33,27,30,26,30,30,30,3rd
13,13,Millard Fillmore,Whig,40,37,36,38,35,38,32,...,39,37,37,37,37,33,37,38,39,4th
14,14,Franklin Pierce,Democratic,38,39,38,40,39,38,39,...,41,40,39,41,39,38,40,40,41,4th
15,15,James Buchanan,Democratic,36,43,40,39,42,41,40,...,43,42,43,44,43,44,44,43,43,4th
16,16,Abraham Lincoln,Republican,28,1,2,2,18,1,1,...,3,4,2,1,6,2,1,3,3,1st
17,17,Andrew Johnson,Democratic,42,42,41,42,40,34,43,...,44,43,42,43,41,43,43,44,44,4th
18,18,Ulysses S. Grant,Republican,20,24,25,24,26,18,17,...,24,26,38,24,24,31,24,24,24,3rd
19,19,Rutherford B. Hayes,Republican,35,30,32,29,23,35,23,...,27,22,30,35,31,28,29,32,32,3rd
20,20,James A. Garfield,Republican,22,25,21,20,41,30,25,...,34,29,27,34,34,27,25,28,29,3rd
21,21,Chester A. Arthur,Republican,41,31,37,36,17,33,22,...,33,30,31,25,32,23,31,34,34,4th
22,22/24,Grover Cleveland,Democratic,26,23,26,27,19,27,22,...,20,21,23,23,21,15,22,23,23,3rd
23,23,Benjamin Harrison,Republican,33,34,30,35,28,36,33,...,35,32,34,32,29,29,33,35,36,4th
24,25,William McKinley,Republican,29,20,20,26,32,22,21,...,23,16,17,20,14,13,20,20,20,2nd
25,26,Theodore Roosevelt,Republican,5,4,8,6,2,2,15,...,9,3,5,4,3,5,4,4,4,1st
26,27,William Howard Taft,Republican,12,28,12,14,27,31,19,...,16,19,21,18,22,19,23,22,22,2nd
27,28,Woodrow Wilson,Democratic,8,8,19,7,14,11,35,...,13,11,14,14,11,25,15,11,12,2nd
28,29,Warren G. Harding,Republican,39,41,42,43,33,40,34,...,36,35,41,38,36,39,41,41,40,4th
29,30,Calvin Coolidge,Republican,32,36,17,33,13,39,27,...,31,24,32,33,35,22,32,31,31,3rd
30,31,Herbert Hoover,Republican,13,35,15,13,43,37,36,...,26,44,35,39,33,40,35,36,35,4th
31,32,Franklin D. Roosevelt,Democratic,6,3,16,12,5,3,4,...,2,2,3,3,1,4,3,2,2,1st
32,33,Harry S. Truman,Democratic,31,16,9,21,12,8,12,...,17,8,10,7,4,9,7,9,9,1st
33,34,Dwight D. Eisenhower,Republican,11,18,5,17,7,21,5,...,5,6,11,8,7,3,6,6,6,1st
34,35,John F. Kennedy,Democratic,14,5,31,11,31,9,8,...,12,7,6,15,17,18,12,10,10,1st
35,36,Lyndon B. Johnson,Democratic,15,11,34,22,25,10,9,...,8,12,8,5,40,35,17,16,16,2nd
36,37,Richard Nixon,Republican,16,21,43,16,36,12,30,...,32,23,28,22,16,42,38,29,28,3rd
37,38,Gerald Ford,Republican,18,32,10,30,30,29,11,...,21,33,24,31,28,21,27,27,26,3rd
38,39,Jimmy Carter,Democratic,25,19,3,15,38,27,29,...,19,38,22,28,25,34,26,26,27,3rd
39,40,Ronald Reagan,Republican,27,17,24,31,3,13,10,...,18,18,20,16,12,12,16,13,14,2nd
40,41,George H. W. Bush,Republican,10,27,18,19,20,27,13,...,29,28,19,26,10,17,21,21,21,2nd
41,42,Bill Clinton,Democratic,21,12,39,8,11,17,3,...,10,5,12,9,18,30,14,15,15,2nd
42,43,George W. Bush,Republican,17,29,33,41,21,20,28,...,28,36,29,30,38,36,34,33,33,3rd
43,44,Barack Obama,Democratic,24,11,13,9,15,23,16,...,14,10,13,13,20,10,11,17,17,2nd
44,45,Donald Trump,Republican,43,40,44,44,10,25,42,...,40,39,44,40,42,41,42,42,42,4th

In [44]:
# Exercise 3:
# Pull out the last two columns by name
(pres[['Average_rank', 'Quartile']])

    Average_rank Quartile
1              1      1st
2             13      2nd
3              5      1st
4              7      1st
5              8      1st
6             18      2nd
7             19      2nd
8             25      3rd
9             38      4th
10            37      4th
11            11      1st
12            30      3rd
13            39      4th
14            41      4th
15            43      4th
16             3      1st
17            44      4th
18            24      3rd
19            32      3rd
20            29      3rd
21            34      4th
22            23      3rd
23            36      4th
24            20      2nd
25             4      1st
26            22      2nd
27            12      2nd
28            40      4th
29            31      3rd
30            35      4th
31             2      1st
32             9      1st
33             6      1st
34            10      1st
35            16      2nd
36            28      3rd
37            26      3rd
38            27      3rd
39            14      2nd
40            21      2nd
41            15      2nd
42            33      3rd
43            17      2nd
44            42      4th

In [55]:
# Exercise 4:
# Pull out the last two columns by position
(pres
 .iloc[:, -2:])

    Average_rank Quartile
1              1      1st
2             13      2nd
3              5      1st
4              7      1st
5              8      1st
6             18      2nd
7             19      2nd
8             25      3rd
9             38      4th
10            37      4th
11            11      1st
12            30      3rd
13            39      4th
14            41      4th
15            43      4th
16             3      1st
17            44      4th
18            24      3rd
19            32      3rd
20            29      3rd
21            34      4th
22            23      3rd
23            36      4th
24            20      2nd
25             4      1st
26            22      2nd
27            12      2nd
28            40      4th
29            31      3rd
30            35      4th
31             2      1st
32             9      1st
33             6      1st
34            10      1st
35            16      2nd
36            28      3rd
37            26      3rd
38            27      3rd
39            14      2nd
40            21      2nd
41            15      2nd
42            33      3rd
43            17      2nd
44            42      4th