In [1]:
import pandas as pd
import numpy as np

In [2]:
def tweak_siena_pres(df):
    def int64_to_uint8(df_):
        cols = df_.select_dtypes('int64')
        return (df_
                .astype({col:'uint8[pyarrow]' for col in cols}))
    return (df
            .rename(columns={'Seq.': 'Seq'}) # 1
            .rename(columns={k:v.replace(' ', '_') for k,v in
                             {'Bg': 'Background',
                              'PL': 'Party leadership', 'CAb': 'Communication ability',
                              'RC': 'Relations with Congress', 'CAp': 'Court appointments',
                              'HE': 'Handling of economy', 'L': 'Luck',
                              'AC': 'Ability to compromise', 'WR': 'Willing to take risks',
                              'EAp': 'Executive appointments', 'OA': 'Overall ability',
                              'Im': 'Imagination', 'DA': 'Domestic accomplishments',
                              'Int': 'Integrity', 'EAb': 'Executive ability',
                              'FPA': 'Foreign policy accomplishments',
                              'LA': 'Leadership ability',
                              'IQ': 'Intelligence', 'AM': 'Avoid crucial mistakes',
                              'EV': "Experts' view", 'O': 'Overall'}.items()})
                              .astype({'Party':'category'})  # 2
                              .pipe(int64_to_uint8)  # 3
                              .assign(Average_rank=lambda df_:(df_.select_dtypes('uint8')
                                                               .sum(axis=1).rank(method='dense').astype('uint8[pyarrow]')),
                                                               Quartile=lambda df_:pd.qcut(df_.Average_rank, 4,
                                                                                           labels='1st 2nd 3rd 4th'.split())
                                    )
    )

In [3]:
url = 'https://github.com/mattharrison/datasets/raw/master/data/siena2018-pres.csv'

In [4]:
df = pd.read_csv(url, index_col=0, dtype_backend='pyarrow')
pres = tweak_siena_pres(df)

In [5]:
pres.isna()

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
pres.isna().any()

Seq                               False
President                         False
Party                             False
Background                        False
Imagination                       False
Integrity                         False
Intelligence                      False
Luck                              False
Willing_to_take_risks             False
Ability_to_compromise             False
Executive_ability                 False
Leadership_ability                False
Communication_ability             False
Overall_ability                   False
Party_leadership                  False
Relations_with_Congress           False
Court_appointments                False
Handling_of_economy               False
Executive_appointments            False
Domestic_accomplishments          False
Foreign_policy_accomplishments    False
Avoid_crucial_mistakes            False
Experts'_view                     False
Overall                           False
Average_rank                      False
Quartile                          False
dtype: bool

In [7]:
print(pres[pres.Integrity.isna()])

Empty DataFrame
Columns: [Seq, President, Party, Background, Imagination, Integrity, Intelligence, Luck, Willing_to_take_risks, Ability_to_compromise, Executive_ability, Leadership_ability, Communication_ability, Overall_ability, Party_leadership, Relations_with_Congress, Court_appointments, Handling_of_economy, Executive_appointments, Domestic_accomplishments, Foreign_policy_accomplishments, Avoid_crucial_mistakes, Experts'_view, Overall, Average_rank, Quartile]
Index: []

[0 rows x 26 columns]

In [8]:
print(pres.query('Integrity.isna()'))

Empty DataFrame
Columns: [Seq, President, Party, Background, Imagination, Integrity, Intelligence, Luck, Willing_to_take_risks, Ability_to_compromise, Executive_ability, Leadership_ability, Communication_ability, Overall_ability, Party_leadership, Relations_with_Congress, Court_appointments, Handling_of_economy, Executive_appointments, Domestic_accomplishments, Foreign_policy_accomplishments, Avoid_crucial_mistakes, Experts'_view, Overall, Average_rank, Quartile]
Index: []

[0 rows x 26 columns]

In [9]:
pres.isna().sum()

Seq                               0
President                         0
Party                             0
Background                        0
Imagination                       0
Integrity                         0
Intelligence                      0
Luck                              0
Willing_to_take_risks             0
Ability_to_compromise             0
Executive_ability                 0
Leadership_ability                0
Communication_ability             0
Overall_ability                   0
Party_leadership                  0
Relations_with_Congress           0
Court_appointments                0
Handling_of_economy               0
Executive_appointments            0
Domestic_accomplishments          0
Foreign_policy_accomplishments    0
Avoid_crucial_mistakes            0
Experts'_view                     0
Overall                           0
Average_rank                      0
Quartile                          0
dtype: int64

In [10]:
pres.isna().mean()

Seq                               0.0
President                         0.0
Party                             0.0
Background                        0.0
Imagination                       0.0
Integrity                         0.0
Intelligence                      0.0
Luck                              0.0
Willing_to_take_risks             0.0
Ability_to_compromise             0.0
Executive_ability                 0.0
Leadership_ability                0.0
Communication_ability             0.0
Overall_ability                   0.0
Party_leadership                  0.0
Relations_with_Congress           0.0
Court_appointments                0.0
Handling_of_economy               0.0
Executive_appointments            0.0
Domestic_accomplishments          0.0
Foreign_policy_accomplishments    0.0
Avoid_crucial_mistakes            0.0
Experts'_view                     0.0
Overall                           0.0
Average_rank                      0.0
Quartile                          0.0
dtype: float64

In [11]:
pres.drop_duplicates()

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
2,2,John Adams,Federalist,3,13,4,4,24,14,31,...,4,13,15,19,13,16,10,14,13,2nd
3,3,Thomas Jefferson,Democratic-Republican,2,2,14,1,8,5,14,...,7,20,4,6,9,7,5,5,5,1st
4,4,James Madison,Democratic-Republican,4,6,7,3,16,15,6,...,6,14,7,11,19,11,8,7,7,1st
5,5,James Monroe,Democratic-Republican,9,14,11,18,6,16,7,...,11,9,9,10,5,6,9,8,8,1st
6,6,John Quincy Adams,Democratic-Republican,1,9,6,5,29,19,24,...,15,17,18,21,15,14,18,18,18,2nd
7,7,Andrew Jackson,Democratic,37,15,29,28,4,4,38,...,30,25,25,17,23,20,19,19,19,2nd
8,8,Martin Van Buren,Democratic,23,22,27,25,34,28,20,...,25,31,26,29,27,24,28,25,25,3rd
9,9,William Henry Harrison,Whig,22,38,28,37,44,32,41,...,42,41,40,42,44,37,39,39,38,4th
10,10,John Tyler,Independent,34,33,35,34,22,26,37,...,38,34,36,36,26,32,36,37,37,4th
11,11,James K. Polk,Democratic,19,10,23,23,9,7,18,...,22,15,16,12,8,8,13,12,11,1st
12,12,Zachary Taylor,Whig,30,26,22,32,37,24,26,...,37,27,33,27,30,26,30,30,30,3rd
13,13,Millard Fillmore,Whig,40,37,36,38,35,38,32,...,39,37,37,37,37,33,37,38,39,4th
14,14,Franklin Pierce,Democratic,38,39,38,40,39,38,39,...,41,40,39,41,39,38,40,40,41,4th
15,15,James Buchanan,Democratic,36,43,40,39,42,41,40,...,43,42,43,44,43,44,44,43,43,4th
16,16,Abraham Lincoln,Republican,28,1,2,2,18,1,1,...,3,4,2,1,6,2,1,3,3,1st
17,17,Andrew Johnson,Democratic,42,42,41,42,40,34,43,...,44,43,42,43,41,43,43,44,44,4th
18,18,Ulysses S. Grant,Republican,20,24,25,24,26,18,17,...,24,26,38,24,24,31,24,24,24,3rd
19,19,Rutherford B. Hayes,Republican,35,30,32,29,23,35,23,...,27,22,30,35,31,28,29,32,32,3rd
20,20,James A. Garfield,Republican,22,25,21,20,41,30,25,...,34,29,27,34,34,27,25,28,29,3rd
21,21,Chester A. Arthur,Republican,41,31,37,36,17,33,22,...,33,30,31,25,32,23,31,34,34,4th
22,22/24,Grover Cleveland,Democratic,26,23,26,27,19,27,22,...,20,21,23,23,21,15,22,23,23,3rd
23,23,Benjamin Harrison,Republican,33,34,30,35,28,36,33,...,35,32,34,32,29,29,33,35,36,4th
24,25,William McKinley,Republican,29,20,20,26,32,22,21,...,23,16,17,20,14,13,20,20,20,2nd
25,26,Theodore Roosevelt,Republican,5,4,8,6,2,2,15,...,9,3,5,4,3,5,4,4,4,1st
26,27,William Howard Taft,Republican,12,28,12,14,27,31,19,...,16,19,21,18,22,19,23,22,22,2nd
27,28,Woodrow Wilson,Democratic,8,8,19,7,14,11,35,...,13,11,14,14,11,25,15,11,12,2nd
28,29,Warren G. Harding,Republican,39,41,42,43,33,40,34,...,36,35,41,38,36,39,41,41,40,4th
29,30,Calvin Coolidge,Republican,32,36,17,33,13,39,27,...,31,24,32,33,35,22,32,31,31,3rd
30,31,Herbert Hoover,Republican,13,35,15,13,43,37,36,...,26,44,35,39,33,40,35,36,35,4th
31,32,Franklin D. Roosevelt,Democratic,6,3,16,12,5,3,4,...,2,2,3,3,1,4,3,2,2,1st
32,33,Harry S. Truman,Democratic,31,16,9,21,12,8,12,...,17,8,10,7,4,9,7,9,9,1st
33,34,Dwight D. Eisenhower,Republican,11,18,5,17,7,21,5,...,5,6,11,8,7,3,6,6,6,1st
34,35,John F. Kennedy,Democratic,14,5,31,11,31,9,8,...,12,7,6,15,17,18,12,10,10,1st
35,36,Lyndon B. Johnson,Democratic,15,11,34,22,25,10,9,...,8,12,8,5,40,35,17,16,16,2nd
36,37,Richard Nixon,Republican,16,21,43,16,36,12,30,...,32,23,28,22,16,42,38,29,28,3rd
37,38,Gerald Ford,Republican,18,32,10,30,30,29,11,...,21,33,24,31,28,21,27,27,26,3rd
38,39,Jimmy Carter,Democratic,25,19,3,15,38,27,29,...,19,38,22,28,25,34,26,26,27,3rd
39,40,Ronald Reagan,Republican,27,17,24,31,3,13,10,...,18,18,20,16,12,12,16,13,14,2nd
40,41,George H. W. Bush,Republican,10,27,18,19,20,27,13,...,29,28,19,26,10,17,21,21,21,2nd
41,42,Bill Clinton,Democratic,21,12,39,8,11,17,3,...,10,5,12,9,18,30,14,15,15,2nd
42,43,George W. Bush,Republican,17,29,33,41,21,20,28,...,28,36,29,30,38,36,34,33,33,3rd
43,44,Barack Obama,Democratic,24,11,13,9,15,23,16,...,14,10,13,13,20,10,11,17,17,2nd
44,45,Donald Trump,Republican,43,40,44,44,10,25,42,...,40,39,44,40,42,41,42,42,42,4th

In [12]:
pres.drop_duplicates(subset='Party')

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,1,2,2,1,2,1,1,1st
2,2,John Adams,Federalist,3,13,4,4,24,14,31,...,4,13,15,19,13,16,10,14,13,2nd
3,3,Thomas Jefferson,Democratic-Republican,2,2,14,1,8,5,14,...,7,20,4,6,9,7,5,5,5,1st
7,7,Andrew Jackson,Democratic,37,15,29,28,4,4,38,...,30,25,25,17,23,20,19,19,19,2nd
9,9,William Henry Harrison,Whig,22,38,28,37,44,32,41,...,42,41,40,42,44,37,39,39,38,4th
16,16,Abraham Lincoln,Republican,28,1,2,2,18,1,1,...,3,4,2,1,6,2,1,3,3,1st

In [13]:
pres.drop_duplicates(subset='Party', keep='last')

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Court_appointments,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile
2,2,John Adams,Federalist,3,13,4,4,24,14,31,...,4,13,15,19,13,16,10,14,13,2nd
6,6,John Quincy Adams,Democratic-Republican,1,9,6,5,29,19,24,...,15,17,18,21,15,14,18,18,18,2nd
10,10,John Tyler,Independent,34,33,35,34,22,26,37,...,38,34,36,36,26,32,36,37,37,4th
13,13,Millard Fillmore,Whig,40,37,36,38,35,38,32,...,39,37,37,37,37,33,37,38,39,4th
43,44,Barack Obama,Democratic,24,11,13,9,15,23,16,...,14,10,13,13,20,10,11,17,17,2nd
44,45,Donald Trump,Republican,43,40,44,44,10,25,42,...,40,39,44,40,42,41,42,42,42,4th

In [14]:
(pres
 .assign(first_in_part_seq= lambda df_: # creates a new column 
         df_.Party != df_.Party.shift(1)) # whenever the party stays the same to the previous one, it will return false, otherwise true
         .query('first_in_part_seq') # will drop everything that is false
         )

,Seq,President,Party,Background,Imagination,Integrity,Intelligence,Luck,Willing_to_take_risks,Ability_to_compromise,...,Handling_of_economy,Executive_appointments,Domestic_accomplishments,Foreign_policy_accomplishments,Avoid_crucial_mistakes,Experts'_view,Overall,Average_rank,Quartile,first_in_part_seq
1,1,George Washington,Independent,7,7,1,10,1,6,2,...,1,1,2,2,1,2,1,1,1st,True
2,2,John Adams,Federalist,3,13,4,4,24,14,31,...,13,15,19,13,16,10,14,13,2nd,True
3,3,Thomas Jefferson,Democratic-Republican,2,2,14,1,8,5,14,...,20,4,6,9,7,5,5,5,1st,True
7,7,Andrew Jackson,Democratic,37,15,29,28,4,4,38,...,25,25,17,23,20,19,19,19,2nd,True
9,9,William Henry Harrison,Whig,22,38,28,37,44,32,41,...,41,40,42,44,37,39,39,38,4th,True
10,10,John Tyler,Independent,34,33,35,34,22,26,37,...,34,36,36,26,32,36,37,37,4th,True
11,11,James K. Polk,Democratic,19,10,23,23,9,7,18,...,15,16,12,8,8,13,12,11,1st,True
12,12,Zachary Taylor,Whig,30,26,22,32,37,24,26,...,27,33,27,30,26,30,30,30,3rd,True
14,14,Franklin Pierce,Democratic,38,39,38,40,39,38,39,...,40,39,41,39,38,40,40,41,4th,True
16,16,Abraham Lincoln,Republican,28,1,2,2,18,1,1,...,4,2,1,6,2,1,3,3,1st,True
17,17,Andrew Johnson,Democratic,42,42,41,42,40,34,43,...,43,42,43,41,43,43,44,44,4th,True
18,18,Ulysses S. Grant,Republican,20,24,25,24,26,18,17,...,26,38,24,24,31,24,24,24,3rd,True
22,22/24,Grover Cleveland,Democratic,26,23,26,27,19,27,22,...,21,23,23,21,15,22,23,23,3rd,True
23,23,Benjamin Harrison,Republican,33,34,30,35,28,36,33,...,32,34,32,29,29,33,35,36,4th,True
27,28,Woodrow Wilson,Democratic,8,8,19,7,14,11,35,...,11,14,14,11,25,15,11,12,2nd,True
28,29,Warren G. Harding,Republican,39,41,42,43,33,40,34,...,35,41,38,36,39,41,41,40,4th,True
31,32,Franklin D. Roosevelt,Democratic,6,3,16,12,5,3,4,...,2,3,3,1,4,3,2,2,1st,True
33,34,Dwight D. Eisenhower,Republican,11,18,5,17,7,21,5,...,6,11,8,7,3,6,6,6,1st,True
34,35,John F. Kennedy,Democratic,14,5,31,11,31,9,8,...,7,6,15,17,18,12,10,10,1st,True
36,37,Richard Nixon,Republican,16,21,43,16,36,12,30,...,23,28,22,16,42,38,29,28,3rd,True
38,39,Jimmy Carter,Democratic,25,19,3,15,38,27,29,...,38,22,28,25,34,26,26,27,3rd,True
39,40,Ronald Reagan,Republican,27,17,24,31,3,13,10,...,18,20,16,12,12,16,13,14,2nd,True
41,42,Bill Clinton,Democratic,21,12,39,8,11,17,3,...,5,12,9,18,30,14,15,15,2nd,True
42,43,George W. Bush,Republican,17,29,33,41,21,20,28,...,36,29,30,38,36,34,33,33,3rd,True
43,44,Barack Obama,Democratic,24,11,13,9,15,23,16,...,10,13,13,20,10,11,17,17,2nd,True
44,45,Donald Trump,Republican,43,40,44,44,10,25,42,...,39,44,40,42,41,42,42,42,4th,True

## Exercises
With a dataset of your choice:
1. Find out which columns have missing data.
2. Count the number of missing values for each column.
3. Find the percentage of missing values for each column.
4. Find the rows with missing data.
5. Find the rows that are duplicated.

In [15]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

cafe = kagglehub.dataset_load(
    handle="ahmedmohamed2003/cafe-sales-dirty-data-for-cleaning-training",
    path="dirty_cafe_sales.csv",
    adapter=KaggleDatasetAdapter.PANDAS
)

In [16]:
for x in cafe.columns:
    print(cafe[str(x)].value_counts(dropna=False))

Transaction ID
TXN_1961373    1
TXN_4831525    1
TXN_1228927    1
TXN_6486912    1
TXN_3447069    1
              ..
TXN_5680238    1
TXN_7766134    1
TXN_2617257    1
TXN_8993132    1
TXN_6170729    1
Name: count, Length: 10000, dtype: int64
Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64
Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
NaN         138
Name: count, dtype: int64
Price Per Unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
NaN         179
UNKNOWN     164
Name: count, dtype: int64
Total Spent
6.0        979
12.0       939
3.0        930
4.0        923
20.0       746
15.0       734
8.0        677
10.0       524
2.0        497
9.0        479
5.0        468
16.0       444
25.0       259
7.5        237
1.0        232
4.5        225
1.5        205
NaN        173
UNKNOWN    165
ERROR      164
Name: count, dtype: int64
Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64
Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64
Transaction Date
UNKNOWN       159
NaN           159
ERROR         142
2023-06-16     40
2023-02-06     40
             ...
2023-04-27     15
2023-09-24     15
2023-07-22     14
2023-03-11     14
2023-02-17     14
Name: count, Length: 368, dtype: int64

In [17]:
cafe = cafe.replace(['UNKNOWN', 'ERROR', np.nan], pd.NA)

for x in cafe.columns:
    print(cafe[str(x)].value_counts(dropna=False))

Transaction ID
TXN_1961373    1
TXN_4831525    1
TXN_1228927    1
TXN_6486912    1
TXN_3447069    1
              ..
TXN_5680238    1
TXN_7766134    1
TXN_2617257    1
TXN_8993132    1
TXN_6170729    1
Name: count, Length: 10000, dtype: int64
Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
<NA>         969
Name: count, dtype: int64
Quantity
5       2013
2       1974
4       1863
3       1849
1       1822
<NA>     479
Name: count, dtype: int64
Price Per Unit
3.0     2429
4.0     2331
2.0     1227
5.0     1204
1.0     1143
1.5     1133
<NA>     533
Name: count, dtype: int64
Total Spent
6.0     979
12.0    939
3.0     930
4.0     923
20.0    746
15.0    734
8.0     677
10.0    524
<NA>    502
2.0     497
9.0     479
5.0     468
16.0    444
25.0    259
7.5     237
1.0     232
4.5     225
1.5     205
Name: count, dtype: int64
Payment Method
<NA>              3178
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64
Location
<NA>        3961
Takeaway    3022
In-store    3017
Name: count, dtype: int64
Transaction Date
<NA>          460
2023-02-06     40
2023-06-16     40
2023-03-13     39
2023-07-21     39
             ...
2023-04-27     15
2023-11-24     15
2023-03-11     14
2023-02-17     14
2023-07-22     14
Name: count, Length: 366, dtype: int64

In [18]:
cafe.isna().any()

Transaction ID      False
Item                 True
Quantity             True
Price Per Unit       True
Total Spent          True
Payment Method       True
Location             True
Transaction Date     True
dtype: bool

In [19]:
cafe.isna().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [20]:
cafe.isna().mean().mul(100).round(1)

Transaction ID       0.0
Item                 9.7
Quantity             4.8
Price Per Unit       5.3
Total Spent          5.0
Payment Method      31.8
Location            39.6
Transaction Date     4.6
dtype: float64

In [21]:
cafe[cafe.isna().any(axis=1)]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2,TXN_4271903,Cookie,4,1.0,<NA>,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,<NA>,<NA>,2023-04-27
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,<NA>,2023-03-31
6,TXN_4433211,<NA>,3,3.0,9.0,<NA>,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,<NA>,2023-10-28
...,...,...,...,...,...,...,...,...
9994,TXN_7851634,<NA>,4,4.0,16.0,<NA>,<NA>,2023-01-08
9995,TXN_7672686,Coffee,2,2.0,4.0,<NA>,<NA>,2023-08-30
9996,TXN_9659401,<NA>,3,<NA>,3.0,Digital Wallet,<NA>,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,<NA>,2023-03-02
9998,TXN_7695629,Cookie,3,<NA>,3.0,Digital Wallet,<NA>,2023-12-02

In [22]:
cafe.shape

(10000, 8)

In [23]:
cafe.drop_duplicates().shape # showing no identical duplicates

(10000, 8)

In [24]:
# toy example: treating same combinations of item and quantity as duplicates
cafe.drop_duplicates(subset=['Item', 'Quantity'])

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,<NA>,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,<NA>,<NA>,2023-04-27
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,<NA>,2023-03-31
6,TXN_4433211,<NA>,3,3.0,9.0,<NA>,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,<NA>,2023-10-28
8,TXN_4717867,<NA>,5,3.0,15.0,<NA>,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,<NA>,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,<NA>
13,TXN_9437049,Cookie,5,1.0,5.0,<NA>,Takeaway,2023-06-01
14,TXN_8915701,<NA>,2,1.5,3.0,<NA>,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,<NA>,<NA>,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,<NA>,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,<NA>,4.0,20.0,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
25,TXN_7958992,Smoothie,3,4.0,<NA>,<NA>,<NA>,2023-12-13
34,TXN_8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
36,TXN_6855453,<NA>,4,3.0,12.0,<NA>,In-store,2023-07-17
39,TXN_6688524,Coffee,4,2.0,8.0,<NA>,<NA>,2023-06-29
42,TXN_6650263,Tea,2,1.5,<NA>,<NA>,Takeaway,2023-01-10
44,TXN_1491578,Cookie,2,1.0,2.0,<NA>,<NA>,2023-02-23
47,TXN_9499313,Juice,5,3.0,15.0,<NA>,<NA>,2023-03-02
49,TXN_8230936,Cake,3,3.0,9.0,<NA>,<NA>,2023-05-02
55,TXN_5522862,Cookie,<NA>,1.0,2.0,Credit Card,Takeaway,2023-03-19
57,TXN_2080895,Cake,<NA>,3.0,3.0,Digital Wallet,In-store,2023-04-19
60,TXN_9023317,Salad,1,5.0,5.0,<NA>,<NA>,2023-09-30
61,TXN_8051289,<NA>,1,3.0,3.0,<NA>,In-store,2023-10-09
66,TXN_8501819,Juice,<NA>,3.0,6.0,Cash,<NA>,2023-03-30
67,TXN_3068204,Cookie,1,1.0,1.0,Credit Card,Takeaway,2023-10-03
71,TXN_4726376,Cake,2,3.0,6.0,Credit Card,In-store,2023-01-31
75,TXN_6420335,Coffee,1,2.0,2.0,Cash,Takeaway,2023-07-16
78,TXN_8735480,Tea,5,1.5,7.5,Cash,<NA>,2023-06-02
85,TXN_8035512,Tea,3,<NA>,4.5,Cash,<NA>,2023-10-29
93,TXN_3011323,Coffee,3,2.0,6.0,Credit Card,<NA>,2023-03-07
94,TXN_6289610,Juice,3,3.0,<NA>,Cash,Takeaway,2023-08-07
105,TXN_6955416,Salad,4,5.0,20.0,<NA>,In-store,2023-02-25
106,TXN_3775339,Cookie,3,1.0,3.0,Credit Card,<NA>,2023-04-03
109,TXN_4174591,Tea,4,1.5,6.0,Digital Wallet,<NA>,2023-08-30
114,TXN_3092382,Coffee,5,2.0,10.0,Digital Wallet,<NA>,2023-02-21
130,TXN_2277042,Tea,1,1.5,1.5,Cash,<NA>,2023-04-08
143,TXN_8495063,Juice,1,3.0,<NA>,Cash,<NA>,2023-05-31
153,TXN_6541415,<NA>,<NA>,3.0,12.0,Cash,In-store,2023-11-25
177,TXN_1896955,Salad,<NA>,5.0,25.0,<NA>,In-store,2023-09-23
191,TXN_8810894,Smoothie,1,4.0,4.0,<NA>,<NA>,2023-02-20
213,TXN_8587583,Cake,1,<NA>,3.0,<NA>,<NA>,2023-10-01
274,TXN_4865338,Sandwich,<NA>,4.0,16.0,<NA>,In-store,2023-11-26
287,TXN_2305908,Coffee,<NA>,2.0,8.0,Cash,<NA>,2023-04-25
438,TXN_3871837,Tea,<NA>,1.5,4.5,Digital Wallet,Takeaway,2023-12-15